rules:
  dangerous-triggers:
    disable: true
  dependabot-cooldown:
    disable: true
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        docker/*: ref-pin
        elastic/*: ref-pin
        github/*: ref-pin
        google/*: ref-pin
        google-github-actions/*: ref-pin
        hashicorp/*: ref-pin
        octokit/*: ref-pin
        ruby/*: ref-pin
        slackapi/*: ref-pin
